<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="UK-C02WF0X2HV2R" name="Onboarding_tests.SetUpTests" tests="11" failures="1" timestamp="27 Aug 2018 16:18:54 GMT" time="458.894" errors="0">
  <testcase name="CUICE4445" time="24.475" classname="Onboarding_tests.SetUpTests"/>
  <testcase name="CUICE4446" time="27.816" classname="Onboarding_tests.SetUpTests"/>
  <testcase name="CUICE4447" time="28.304" classname="Onboarding_tests.SetUpTests"/>
  <testcase name="CUICE4448" time="38.393" classname="Onboarding_tests.SetUpTests"/>
  <testcase name="CUICE4343" time="29.149" classname="Onboarding_tests.SetUpTests"/>
  <testcase name="CUICE4344" time="30.723" classname="Onboarding_tests.SetUpTests"/>
  <testcase name="CUICE4345" time="79.189" classname="Onboarding_tests.SetUpTests"/>
  <testcase name="CUICE4346" time="78.774" classname="Onboarding_tests.SetUpTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at Onboarding_tests.SetUpTests.CUICE4346(SetUpTests.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
    </failure>
  </testcase> <!-- CUICE4346 -->
  <testcase name="CUICE4105" time="38.664" classname="Onboarding_tests.SetUpTests"/>
  <testcase name="CUICE4815" time="41.477" classname="Onboarding_tests.SetUpTests"/>
  <testcase name="CUICE4816" time="41.930" classname="Onboarding_tests.SetUpTests"/>
</testsuite> <!-- Onboarding_tests.SetUpTests -->
